### ISSUE TITLE
Failed to install  No package 'pangocairo' found 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/setup-cml#48] opened 2021-09-20 22:09 UTC
```sh
Uninstalling previous CML
Installing CML version latest
Error: Command failed: /usr/bin/sudo npm install -g canvas@2 vega@5 vega-cli@5 vega-lite@4 @dvcorg/cml
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
../deps/libmagic/src/readelf.c: In function ‘dophn_core’:
../deps/libmagic/src/readelf.c:1024:13: warning: ‘nh64.n_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1024 |  Elf64_Nhdr nh64;
      |             ^~~~
../deps/libmagic/src/readelf.c:1023:13: warning: ‘nh32.n_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1023 |  Elf32_Nhdr nh32;
      |             ^~~~
../deps/libmagic/src/readelf.c: In function ‘dophn_exec’:
../deps/libmagic/src/readelf.c:1024:13: warning: ‘nh64.n_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1024 |  Elf64_Nhdr nh64;
      |             ^~~~
../deps/libmagic/src/readelf.c:1023:13: warning: ‘nh32.n_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1023 |  Elf32_Nhdr nh32;
      |             ^~~~
../deps/libmagic/src/readelf.c: In function ‘doshn’:
../deps/libmagic/src/readelf.c:1024:13: warning: ‘nh64.n_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1024 |  Elf64_Nhdr nh64;
      |             ^~~~
../deps/libmagic/src/readelf.c:1023:13: warning: ‘nh32.n_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1023 |  Elf32_Nhdr nh32;
      |             ^~~~
../src/binding.cc: In static member function ‘static void Magic::DetectFile(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:184:59: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  184 |                                  (uv_after_work_cb)Magic::DetectAfter);
      |                                                           ^~~~~~~~~~~
../src/binding.cc: In static member function ‘static void Magic::Detect(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:217:59: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  217 |                                  (uv_after_work_cb)Magic::DetectAfter);
      |                                                           ^~~~~~~~~~~
In file included from ../src/binding.cc:1:
../src/binding.cc: At global scope:
/root/.cache/node-gyp/14.17.6/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/14.17.6/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cc:415:3: note: in expansion of macro ‘NODE_MODULE’
  415 |   NODE_MODULE(magic, init);
      |   ^~~~~~~~~~~
node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.6 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-x64.tar.gz 
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-1041-azure
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /usr/local/lib/node_modules/canvas
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.8.0-1041-azure
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/canvas
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-20T22_07_35_242Z-debug.log
```

**Comment by DavidGOrtega** [comment] 2021-09-20 22:10
Started to fail 5 min ago, it has been working properly all day. Maybe is transient?

**Comment by DavidGOrtega** [comment] 2021-09-20 22:21
adding this step in the workflow seems to fix it, actually only libgif-dev fix it. 🤔 
```yaml
- name: deps
      run: |
        sudo apt update
        sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
```

**Comment by casperdcl** [comment] 2021-09-22 08:33
temporary `403` errors seem fixed now :)

**Comment by 0x2b3bfa0** [comment] 2021-09-22 08:34
Duplicate of https://github.com/iterative/cml/issues/723

**Closed as completed** 2021-09-22 11:54 UTC
Labels: p0-critical, duplicate
